apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slashbay-data
  namespace: slashbay
  labels:
    app: slashbay
    app.kubernetes.io/name: slashbay
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-csi-nfs
  resources:
    requests:
      storage: 1Gi
